services:
  nestjs:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mongodb
    volumes:
      - .:/usr/src/app

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  
  mongodb:
    image: 'mongo:latest'
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
