services:
  nestjs:
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
